name: CI/CD Pipeline for Analytics Microservice

on:
  push:
    paths:
      - 'analytics/**'
      - 'common/**'

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: 831342134505.dkr.ecr.ap-southeast-1.amazonaws.com/analytics

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker build -f analytics/Dockerfile -t ${{ env.ECR_REPOSITORY }}:1.0.0 .
        docker push ${{ env.ECR_REPOSITORY }}:1.0.0

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json
        service: analytics-service
        cluster: your-cluster-name
        wait-for-service-stability: true
